version: '3'

services:
  nginx:
    image: nginx:1.22
    volumes:
      - ./nginx/templates/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./nginx/ssl/:/etc/ssl/
      - ./website/:/var/www/:ro  # so nginx has read-only access to static files
    environment:
      - NGINX_HOSTNAME=${NGINX_HOSTNAME}
    ports:
      - 80:80
      - 443:443
    depends_on:
      - website

  website:
    build: .
    command: gunicorn -b 0.0.0.0:8000 -w 4 --threads 2 'website:init_app()'
    restart: always
    privileged: true
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - celery
      - redis
      - mongo
    volumes:
      - uploads:/uploads
  
  celery:
    build: .
    command: celery -A website.celery_worker.celery worker --loglevel=INFO
    restart: always
    privileged: true
    depends_on:
      - redis
      - mongo
    volumes:
      - uploads:/uploads

  redis:
    image: redis:7.0
    restart: always
    expose:
      - 6379
    command: --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data

  mongo:
    image: mongo:6.0
    restart: always
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - db:/data/db

volumes:
  cache:
  db:
  uploads: